datasets: Explicit the required export-name flag
It's required now, otherwise it will fail [1]

[1]
```
luigi.parameter.MissingParameterException: ExportGraph[args=(), kwargs={'local_export_path': PosixPath('/srv/dataset/2025-05-20'), 'local_sensitive_export_path': PosixPath('/srv/dataset/2025-05-20/sensitive'), 'formats': (<Format.orc: 2>,), 'object_types': (<ObjectType.skipped_content: 9>, <ObjectType.content: 8>, <ObjectType.directory: 7>, <ObjectType.revision: 6>, <ObjectType.r
elease: 5>, <ObjectType.snapshot: 4>, <ObjectType.origin: 1>, <ObjectType.origin_visit: 2>, <ObjectType.origin_visit_status: 3>)}]: requires the 'export_name' parameter to be set

```

Refs. swh/infra/sysadm-environment#5683