alter: Test ceph storage pvc request increase
It should automatically resize the associated volume. Testing it in staging.

Context:
The latest takedown requests initiated yesterday 06/05/2025 around 15h failed during the
night because the "backing up of content objects" step failed [1] [2] due to "disk quota
exceeded". We need to bump the size of the recovery bundle partition.

[1]
```
(venv) swh@tony-alter:~$ df -h /srv/recovery-bundles/
Filesystem                                                                                                                                                   Size  Used Avail Use% Mounted on
host:port,...:/volumes/csi/csi-vol-foo/bar   23G  7.2G  77% /srv/recovery-bundles
```

[2]
$ swh alter ...
Finding removable objects…
Inventorying all reachable objects…  [####################################] (150608 objects found / 2068 left to look up)
Inventorying all reachable objects…  [####################################] done (162669 objects found / 0 left to look up)
Determining which objects can be safely removed…  [####################################]  100%
Finding RawExtrinsicMetadata objects…  [####################################]  100%
Finding more RawExtrinsicMetadata objects…  [####################################]  100%
Removal plan:
- Origin: 249
- Snapshot: 247
- Release: 2
- Revision: 23953
- Directory: 52746
- Content: 39705
- Raw_extrinsic_metadata: 466
- … and more objects that are not addresseable by a SWHID (OriginVisit, OriginVisitStatus, ExtID).
Proceed? [y/N]: y
Creating recovery bundle…
Backing up Content objects…  [################--------------------]   44%  03:42:20
Traceback (most recent call last):
  File "/opt/swh/venv/bin/swh", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/swh/venv/lib/python3.11/site-packages/swh/core/cli/__init__.py", line 176, in main
    return swh(auto_envvar_prefix="SWH")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/swh/venv/lib/python3.11/site-packages/click/core.py", line 1485, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/swh/venv/lib/python3.11/site-packages/click/core.py", line 1406, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/swh/venv/lib/python3.11/site-packages/click/core.py", line 1873, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/swh/venv/lib/python3.11/site-packages/click/core.py", line 1873, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/swh/venv/lib/python3.11/site-packages/click/core.py", line 1269, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/swh/venv/lib/python3.11/site-packages/click/core.py", line 824, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/swh/venv/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/swh/venv/lib/python3.11/site-packages/swh/alter/cli.py", line 510, in remove
    decryption_key = remover.create_recovery_bundle(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/swh/venv/lib/python3.11/site-packages/swh/alter/operations.py", line 325, in create_recovery_bundle
    creator.backup_swhids(
  File "/opt/swh/venv/lib/python3.11/site-packages/swh/alter/recovery_bundle.py", line 1257, in backup_swhids
    for obj in iter_swhids_grouped_by_type(
  File "/opt/swh/venv/lib/python3.11/site-packages/swh/alter/utils.py", line 72, in iter_swhids_grouped_by_type
    yield from handlers[object_type](chunk)
  File "/opt/swh/venv/lib/python3.11/site-packages/swh/alter/recovery_bundle.py", line 1022, in _add_contents
    self._write(
  File "/opt/swh/venv/lib/python3.11/site-packages/swh/alter/recovery_bundle.py", line 973, in _write
    self._zip.writestr(arcname, age_encrypt(self._pk, data))
  File "/usr/local/lib/python3.11/zipfile.py", line 1869, in writestr
    dest.write(data)
  File "/usr/local/lib/python3.11/zipfile.py", line 1196, in write
    self._fileobj.write(data)
OSError: [Errno 122] Disk quota exceeded
```

Note: stuck in git commit message since gitlab refused to let me create a new issue currently.